SERVER_NODE_NAME = 'laballeaS'
SERVER_NODE_IP = '192.168.42.110'

MEM = 1024
CPU = 1
BOX = "ubuntu/bionic64"
BOX_AUTO_UPDATE = false


Vagrant.configure("2") do |config|
	config.vm.box = BOX
	config.vm.box_check_update = BOX_AUTO_UPDATE
  
	config.vm.provider "virtualbox" do |v|
		v.memory = MEM
		v.cpus = CPU
	end

	config.vm.define SERVER_NODE_NAME do |server|
		server.vm.hostname = SERVER_NODE_NAME
		server.vm.network :private_network, ip: SERVER_NODE_IP
		server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		server.vm.provision "shell", privileged: true, path: "scripts/server.sh", args: [SERVER_NODE_IP]

		server.vm.provider "virtualbox" do |v|
			v.name = SERVER_NODE_NAME
		end
	end
end