SERVER_NODE_NAME = 'laballeaS'
SERVER_NODE_IP = '192.168.42.110'

WORKER_NODE_NAME = 'laballeaSW'
WORKER_NODE_IP = '192.168.42.111'

MEM = 1024
CPU = 1
BOX = "ubuntu/bionic64"


Vagrant.configure("2") do |config|
	config.vm.box = BOX
  
	config.vm.provider "virtualbox" do |v|
		v.memory = MEM
		v.cpus = CPU
	end

	config.vm.define SERVER_NODE_NAME do |server|
		server.vm.hostname = SERVER_NODE_NAME
		server.vm.network :private_network, ip: SERVER_NODE_IP
		server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		server.vm.provision "shell", privileged: true, path: "scripts/server.sh", args: [SERVER_NODE_IP]

		server.vm.provider "virtualbox" do |v|
			v.name = SERVER_NODE_NAME
		end
	end

	config.vm.define WORKER_NODE_NAME do |worker|
		worker.vm.hostname = WORKER_NODE_NAME
		worker.vm.network :private_network, ip: WORKER_NODE_IP 
		worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		worker.vm.provision "shell", privileged: true, path: "scripts/worker.sh", args: [SERVER_NODE_IP, WORKER_NODE_IP]

		worker.vm.provider "virtualbox" do |v|
			v.name = WORKER_NODE_NAME
		end
	end
end